apiVersion: apps/v1
kind: Deployment
metadata:
  name: amconsole
  namespace: amconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amconsole
  template:
    metadata:
      labels:
        app: amconsole
    spec:
      containers:
      - name: amconsole
        image: wasilahhadi/amconsole:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: amconsole-config