apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amconsole-ingress
  namespace: amconsole
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - amconsole.store
    secretName: amconsole-tls
  rules:
  - host: amconsole.store
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: amconsole-service
            port:
              number: 80