apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vps-pool
  namespace: metallb-system
spec:
  addresses:
  - 72.61.69.116-72.61.69.116
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: vps-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - vps-pool