apiVersion: v1
kind: Service
metadata:
  name: amconsole-nodeport
  namespace: amconsole
spec:
  type: NodePort
  selector:
    app: amconsole
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080